apiVersion: v1
kind: Service
metadata:
  name: multicast-headless
  labels:
    app: multicast
spec:
  clusterIP: None
  selector:
    app: multicast
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multicast
spec:
  serviceName: multicast-headless
  replicas: 3
  selector:
    matchLabels:
      app: multicast
  template:
    metadata:
      labels:
        app: multicast
    spec:
      containers:
        - name: multicast
          image: multicast:sos          
          imagePullPolicy: Never        
          ports:
            - containerPort: 8000
          env:
            - name: N_PROCS
              value: "3"

            - name: PROC_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: PORT
              value: "8000"

            - name: PEERS
              value: "http://multicast-0.multicast-headless:8000,http://multicast-1.multicast-headless:8000,http://multicast-2.multicast-headless:8000"
            - name: DELAY_PROCESS_ID
              value: "1"
            - name: DELAY_SECONDS
              value: "15"